import { Category, Product } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'fruits-veg',
    name: 'Fresh Fruits & Vegetable',
    fillBg: '#EEF8F2',
    borderColor: '#53B175',
    iconName: 'Apple',
    imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=600&h=450&q=80',
  },
  {
    id: 'oil-ghee',
    name: 'Cooking Oil & Ghee',
    fillBg: '#FFF6EE',
    borderColor: '#F3A747',
    iconName: 'Flame',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&h=450&q=80',
  },
  {
    id: 'meat-fish',
    name: 'Meat & Fish',
    fillBg: '#FDE8E4',
    borderColor: '#F7A593',
    iconName: 'Fish',
    imageUrl: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=600&h=450&q=80',
  },
  {
    id: 'bakery-snacks',
    name: 'Bakery & Snacks',
    fillBg: '#F4EBF7',
    borderColor: '#D3B0E0',
    iconName: 'Cookie',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&h=450&q=80',
  },
  {
    id: 'dairy-eggs',
    name: 'Dairy & Eggs',
    fillBg: '#FEF8E5',
    borderColor: '#FDE598',
    iconName: 'Egg',
    imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=600&h=450&q=80',
  },
  {
    id: 'beverages',
    name: 'Beverages',
    fillBg: '#EDF7FC',
    borderColor: '#B7DFF5',
    iconName: 'CupSoda',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&h=450&q=80',
  },
  {
    id: 'fast-food',
    name: 'Fast Food & Munchies',
    fillBg: '#FDF2F8',
    borderColor: '#F472B6',
    iconName: 'Pizza',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&h=450&q=80',
  },
  {
    id: 'staples-spices',
    name: 'Spices & Staples',
    fillBg: '#FFFBEB',
    borderColor: '#F59E0B',
    iconName: 'Package',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&h=450&q=80',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // ── Exclusive Offers / Fruits & Veg ──
  {
    id: 'p-1',
    name: 'Organic Red Apples',
    categoryId: 'fruits-veg',
    categoryName: 'Fresh Fruits & Vegetable',
    unit: '1kg',
    price: 4.99,
    originalPrice: 5.99,
    rating: 4.8,
    reviewsCount: 124,
    description: 'Fresh, crispy organic red apples sourced directly from sustainable orchards. High in fiber and vitamin C.',
    nutritionInfo: { weight: '1000g', calories: '95 kcal', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 15,
    isExclusive: true,
    isBestSelling: true,
    brand: 'Individual Collection',
  },
  {
    id: 'p-2',
    name: 'Organic Bananas',
    categoryId: 'fruits-veg',
    categoryName: 'Fresh Fruits & Vegetable',
    unit: '7 pcs',
    price: 2.99,
    originalPrice: 3.49,
    rating: 4.9,
    reviewsCount: 210,
    description: 'Naturally sweet and rich in potassium. Perfect for smoothies or healthy daily snacking.',
    nutritionInfo: { weight: '700g', calories: '105 kcal', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1543218024-57a70143c369?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 25,
    isExclusive: true,
    isBestSelling: true,
    brand: 'Individual Collection',
  },
  {
    id: 'p-3',
    name: 'Bell Pepper Red',
    categoryId: 'fruits-veg',
    categoryName: 'Fresh Fruits & Vegetable',
    unit: '1kg',
    price: 2.49,
    rating: 4.6,
    reviewsCount: 88,
    description: 'Vibrant red bell peppers packed with Vitamin A and C. Excellent for stir-fries, salads, and grilling.',
    nutritionInfo: { weight: '1000g', calories: '31 kcal', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 10,
    isExclusive: true,
    brand: 'Kazi Farms',
  },
  {
    id: 'p-4',
    name: 'Ginger Fresh Root',
    categoryId: 'fruits-veg',
    categoryName: 'Fresh Fruits & Vegetable',
    unit: '250g',
    price: 1.99,
    rating: 4.7,
    reviewsCount: 54,
    description: 'Aromatic and pungent fresh ginger root. Adds incredible depth to teas, curries, and dressings.',
    nutritionInfo: { weight: '250g', calories: '80 kcal', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 12,
    isExclusive: true,
    brand: 'Individual Collection',
  },
  {
    id: 'p-14',
    name: 'Fresh Strawberries',
    categoryId: 'fruits-veg',
    categoryName: 'Fresh Fruits & Vegetable',
    unit: '250g',
    price: 3.99,
    originalPrice: 4.49,
    rating: 4.9,
    reviewsCount: 168,
    description: 'Plump, juicy ripe strawberries hand-picked at peak sweetness.',
    nutritionInfo: { weight: '250g', calories: '32 kcal per 100g', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 18,
    isBestSelling: true,
    brand: 'Individual Collection',
  },
  {
    id: 'p-15',
    name: 'Organic Hass Avocados',
    categoryId: 'fruits-veg',
    categoryName: 'Fresh Fruits & Vegetable',
    unit: '3 pcs',
    price: 4.29,
    rating: 4.8,
    reviewsCount: 195,
    description: 'Creamy Hass avocados perfect for guacamole, toast spreads, and healthy salads.',
    nutritionInfo: { weight: '450g', calories: '160 kcal per avocado', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 20,
    isExclusive: true,
    brand: 'Individual Collection',
  },
  {
    id: 'p-16',
    name: 'Fresh Broccoli Crown',
    categoryId: 'fruits-veg',
    categoryName: 'Fresh Fruits & Vegetable',
    unit: '500g',
    price: 2.19,
    rating: 4.6,
    reviewsCount: 92,
    description: 'Nutrient-rich dark green broccoli crowns high in fiber and essential antioxidants.',
    nutritionInfo: { weight: '500g', calories: '55 kcal', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 14,
    brand: 'Kazi Farms',
  },

  // ── Beverages ──
  {
    id: 'p-5',
    name: 'Classic Sparkling Cola',
    categoryId: 'beverages',
    categoryName: 'Beverages',
    unit: '355ml',
    price: 1.49,
    originalPrice: 1.99,
    rating: 4.5,
    reviewsCount: 340,
    description: 'Crisp, refreshing carbonated sparkling beverage with natural cola flavor.',
    nutritionInfo: { weight: '355ml', calories: '140 kcal', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 30,
    isBestSelling: true,
    brand: 'Generic Beverage Co.',
  },
  {
    id: 'p-6',
    name: 'Zero Sugar Cola Can',
    categoryId: 'beverages',
    categoryName: 'Beverages',
    unit: '355ml',
    price: 1.49,
    rating: 4.4,
    reviewsCount: 190,
    description: 'Zero sugar cola offering full classic taste without calories.',
    nutritionInfo: { weight: '355ml', calories: '0 kcal', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 20,
    brand: 'Generic Beverage Co.',
  },
  {
    id: 'p-7',
    name: 'Lemon Lime Citrus Soda',
    categoryId: 'beverages',
    categoryName: 'Beverages',
    unit: '355ml',
    price: 1.29,
    rating: 4.6,
    reviewsCount: 145,
    description: 'Zesty lemon-lime soda for an invigorating burst of citrus flavor.',
    nutritionInfo: { weight: '355ml', calories: '130 kcal', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 18,
    isBestSelling: true,
    brand: 'Generic Beverage Co.',
  },
  {
    id: 'p-8',
    name: 'Natural Apple Juice Box',
    categoryId: 'beverages',
    categoryName: 'Beverages',
    unit: '2L',
    price: 3.99,
    rating: 4.9,
    reviewsCount: 96,
    description: '100% pure pressed apple juice with no added sugar or artificial preservatives.',
    nutritionInfo: { weight: '2000ml', calories: '110 kcal per glass', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1576675466969-38eeae4b41f6?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 8,
    brand: 'Individual Collection',
  },
  {
    id: 'p-9',
    name: 'Orange Juice Fresh Pressed',
    categoryId: 'beverages',
    categoryName: 'Beverages',
    unit: '1L',
    price: 4.49,
    rating: 4.8,
    reviewsCount: 210,
    description: 'Pure sun-ripened orange juice with high pulp and Vitamin C.',
    nutritionInfo: { weight: '1000ml', calories: '120 kcal', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 14,
    isExclusive: true,
    brand: 'Individual Collection',
  },

  // ── Dairy & Eggs ──
  {
    id: 'p-10',
    name: 'Farm Fresh Brown Eggs',
    categoryId: 'dairy-eggs',
    categoryName: 'Dairy & Eggs',
    unit: '12 pcs',
    price: 3.49,
    rating: 4.9,
    reviewsCount: 430,
    description: 'Grade-A pasture raised brown eggs from free-roaming hens.',
    nutritionInfo: { weight: '700g', calories: '70 kcal per egg', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 30,
    isBestSelling: true,
    brand: 'Kazi Farms',
  },
  {
    id: 'p-11',
    name: 'Whole Fresh Milk 1L',
    categoryId: 'dairy-eggs',
    categoryName: 'Dairy & Eggs',
    unit: '1L',
    price: 2.19,
    rating: 4.7,
    reviewsCount: 310,
    description: 'Rich, creamy whole milk pasteurized for peak freshness and calcium content.',
    nutritionInfo: { weight: '1000ml', calories: '150 kcal', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 22,
    isBestSelling: true,
    brand: 'Ifad',
  },
  {
    id: 'p-18',
    name: 'Greek Whole Milk Yogurt',
    categoryId: 'dairy-eggs',
    categoryName: 'Dairy & Eggs',
    unit: '450g',
    price: 3.29,
    rating: 4.8,
    reviewsCount: 142,
    description: 'Thick, velvety Greek yogurt strained to perfection with active live cultures.',
    nutritionInfo: { weight: '450g', calories: '130 kcal per serving', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 16,
    brand: 'Ifad',
  },
  {
    id: 'p-19',
    name: 'Unsalted Creamery Butter',
    categoryId: 'dairy-eggs',
    categoryName: 'Dairy & Eggs',
    unit: '250g',
    price: 3.89,
    rating: 4.9,
    reviewsCount: 175,
    description: 'Rich European-style churned butter made from pure sweet cream.',
    nutritionInfo: { weight: '250g', calories: '100 kcal per tbsp', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 19,
    brand: 'Individual Collection',
  },
  {
    id: 'p-20',
    name: 'Aged Sharp Cheddar',
    categoryId: 'dairy-eggs',
    categoryName: 'Dairy & Eggs',
    unit: '200g',
    price: 4.50,
    rating: 4.7,
    reviewsCount: 118,
    description: 'Naturally aged white cheddar block with a complex, sharp savory bite.',
    nutritionInfo: { weight: '200g', calories: '110 kcal per 30g', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 12,
    brand: 'Individual Collection',
  },

  // ── Meat & Fish ──
  {
    id: 'p-21',
    name: 'Fresh Atlantic Salmon Fillet',
    categoryId: 'meat-fish',
    categoryName: 'Meat & Fish',
    unit: '400g',
    price: 11.99,
    originalPrice: 13.99,
    rating: 4.9,
    reviewsCount: 215,
    description: 'Sustainably farmed Atlantic salmon fillets rich in Omega-3 fatty acids.',
    nutritionInfo: { weight: '400g', calories: '200 kcal per fillet', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 10,
    isExclusive: true,
    isBestSelling: true,
    brand: 'Kazi Farms',
  },
  {
    id: 'p-22',
    name: 'Organic Chicken Breast',
    categoryId: 'meat-fish',
    categoryName: 'Meat & Fish',
    unit: '500g',
    price: 7.49,
    rating: 4.8,
    reviewsCount: 184,
    description: 'Boneless, skinless chicken breasts raised without antibiotics.',
    nutritionInfo: { weight: '500g', calories: '165 kcal per 100g', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 15,
    brand: 'Kazi Farms',
  },

  // ── Cooking Oil & Ghee ──
  {
    id: 'p-12',
    name: 'Extra Virgin Olive Oil',
    categoryId: 'oil-ghee',
    categoryName: 'Cooking Oil & Ghee',
    unit: '500ml',
    price: 8.99,
    originalPrice: 10.49,
    rating: 4.9,
    reviewsCount: 180,
    description: 'Cold-pressed extra virgin olive oil imported from Mediterranean groves.',
    nutritionInfo: { weight: '500ml', calories: '120 kcal per tbsp', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 10,
    isExclusive: true,
    brand: 'Individual Collection',
  },
  {
    id: 'p-23',
    name: 'Pure Organic Cow Ghee',
    categoryId: 'oil-ghee',
    categoryName: 'Cooking Oil & Ghee',
    unit: '500g',
    price: 9.49,
    rating: 4.9,
    reviewsCount: 160,
    description: 'Traditional clarified butter made from 100% organic grass-fed cow milk.',
    nutritionInfo: { weight: '500g', calories: '130 kcal per tbsp', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 12,
    isBestSelling: true,
    brand: 'Ifad',
  },
  {
    id: 'p-24',
    name: 'Cold Pressed Sunflower Oil',
    categoryId: 'oil-ghee',
    categoryName: 'Cooking Oil & Ghee',
    unit: '1L',
    price: 5.99,
    rating: 4.7,
    reviewsCount: 88,
    description: 'Light, high-heat cooking oil packed with natural Vitamin E.',
    nutritionInfo: { weight: '1000ml', calories: '120 kcal per tbsp', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 20,
    brand: 'Individual Collection',
  },

  // ── Bakery & Snacks ──
  {
    id: 'p-13',
    name: 'Egg Noodles Pack',
    categoryId: 'bakery-snacks',
    categoryName: 'Bakery & Snacks',
    unit: '400g',
    price: 1.89,
    rating: 4.6,
    reviewsCount: 165,
    description: 'Quick-cooking wheat egg noodles, ideal for soups and Asian stir-fry recipes.',
    nutritionInfo: { weight: '400g', calories: '350 kcal', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 20,
    brand: 'Ifad',
  },
  {
    id: 'p-17',
    name: 'Whole Wheat Sourdough Bread',
    categoryId: 'bakery-snacks',
    categoryName: 'Bakery & Snacks',
    unit: '500g',
    price: 2.49,
    rating: 4.8,
    reviewsCount: 205,
    description: 'Freshly baked artisanal whole wheat sourdough with a golden crunchy crust.',
    nutritionInfo: { weight: '500g', calories: '80 kcal per slice', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 25,
    isBestSelling: true,
    brand: 'Individual Collection',
  },
  {
    id: 'p-25',
    name: 'Dark Chocolate Chunk Cookies',
    categoryId: 'bakery-snacks',
    categoryName: 'Bakery & Snacks',
    unit: '200g',
    price: 2.99,
    rating: 4.9,
    reviewsCount: 312,
    description: 'Oven-baked crunchy cookies loaded with 70% cocoa dark chocolate chunks.',
    nutritionInfo: { weight: '200g', calories: '140 kcal per cookie', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 30,
    isExclusive: true,
    brand: 'Individual Collection',
  },
  {
    id: 'p-26',
    name: 'Crispy Sea Salt Potato Chips',
    categoryId: 'bakery-snacks',
    categoryName: 'Bakery & Snacks',
    unit: '150g',
    price: 1.79,
    rating: 4.5,
    reviewsCount: 240,
    description: 'Kettle-cooked potato chips seasoned with fine sea salt.',
    nutritionInfo: { weight: '150g', calories: '150 kcal per 30g', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 28,
    brand: 'Generic Beverage Co.',
  },

  // ── Fast Food & Munchies ──
  {
    id: 'p-27',
    name: 'Artisanal Pepperoni Pizza',
    categoryId: 'fast-food',
    categoryName: 'Fast Food & Munchies',
    unit: '450g',
    price: 6.99,
    originalPrice: 7.99,
    rating: 4.8,
    reviewsCount: 155,
    description: 'Stone-baked thin crust pizza topped with spicy pepperoni and mozzarella cheese.',
    nutritionInfo: { weight: '450g', calories: '280 kcal per slice', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 15,
    isExclusive: true,
    brand: 'Individual Collection',
  },
  {
    id: 'p-28',
    name: 'Gourmet Veggie Burger Pack',
    categoryId: 'fast-food',
    categoryName: 'Fast Food & Munchies',
    unit: '4 pcs',
    price: 5.49,
    rating: 4.7,
    reviewsCount: 110,
    description: 'Flavorful plant-based patties crafted from black beans, quinoa, and sweet corn.',
    nutritionInfo: { weight: '400g', calories: '180 kcal per patty', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 12,
    brand: 'Kazi Farms',
  },

  // ── Spices & Staples ──
  {
    id: 'p-29',
    name: 'Premium Aged Basmati Rice',
    categoryId: 'staples-spices',
    categoryName: 'Spices & Staples',
    unit: '2kg',
    price: 8.49,
    originalPrice: 9.99,
    rating: 4.9,
    reviewsCount: 280,
    description: 'Long-grain extra aromatic basmati rice aged for 2 years for fluffiest biryanis.',
    nutritionInfo: { weight: '2000g', calories: '160 kcal per cup cooked', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 20,
    isBestSelling: true,
    brand: 'Ifad',
  },
  {
    id: 'p-30',
    name: 'Organic Ground Turmeric',
    categoryId: 'staples-spices',
    categoryName: 'Spices & Staples',
    unit: '200g',
    price: 2.79,
    rating: 4.8,
    reviewsCount: 135,
    description: 'Pure ground golden turmeric root rich in natural curcumin.',
    nutritionInfo: { weight: '200g', calories: '24 kcal per tbsp', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&h=450&q=80',
    stockQuantity: 18,
    brand: 'Individual Collection',
  },
];
