import { Category, Product } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'fruits-veg',
    name: 'Fresh Fruits & Vegetable',
    fillBg: '#EEF8F2',
    borderColor: '#53B175',
    iconName: 'Apple',
    imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'oil-ghee',
    name: 'Cooking Oil & Ghee',
    fillBg: '#FFF6EE',
    borderColor: '#F3A747',
    iconName: 'Flame',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'meat-fish',
    name: 'Meat & Fish',
    fillBg: '#FDE8E4',
    borderColor: '#F7A593',
    iconName: 'Fish',
    imageUrl: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'bakery-snacks',
    name: 'Bakery & Snacks',
    fillBg: '#F4EBF7',
    borderColor: '#D3B0E0',
    iconName: 'Cookie',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'dairy-eggs',
    name: 'Dairy & Eggs',
    fillBg: '#FEF8E5',
    borderColor: '#FDE598',
    iconName: 'Egg',
    imageUrl: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'beverages',
    name: 'Beverages',
    fillBg: '#EDF7FC',
    borderColor: '#B7DFF5',
    iconName: 'CupSoda',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=400&q=80',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Exclusive Offers / Fruits & Veg
  {
    id: 'p-1',
    name: 'Organic Red Apples',
    categoryId: 'fruits-veg',
    categoryName: 'Fresh Fruits & Vegetable',
    unit: '1kg',
    price: 4.99,
    originalPrice: 5.99,
    rating: 4.8,
    reviewsCount: 124,
    description: 'Fresh, crispy organic red apples sourced directly from sustainable orchards. High in fiber and vitamin C.',
    nutritionInfo: { weight: '1000g', calories: '95 kcal', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=500&q=80',
    stockQuantity: 15,
    isExclusive: true,
    isBestSelling: true,
    brand: 'Individual Collection',
  },
  {
    id: 'p-2',
    name: 'Organic Bananas',
    categoryId: 'fruits-veg',
    categoryName: 'Fresh Fruits & Vegetable',
    unit: '7 pcs',
    price: 2.99,
    originalPrice: 3.49,
    rating: 4.9,
    reviewsCount: 210,
    description: 'Naturally sweet and rich in potassium. Perfect for smoothies or healthy daily snacking.',
    nutritionInfo: { weight: '700g', calories: '105 kcal', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=500&q=80',
    stockQuantity: 25,
    isExclusive: true,
    isBestSelling: true,
    brand: 'Individual Collection',
  },
  {
    id: 'p-3',
    name: 'Bell Pepper Red',
    categoryId: 'fruits-veg',
    categoryName: 'Fresh Fruits & Vegetable',
    unit: '1kg',
    price: 2.49,
    rating: 4.6,
    reviewsCount: 88,
    description: 'Vibrant red bell peppers packed with Vitamin A and C. Excellent for stir-fries, salads, and grilling.',
    nutritionInfo: { weight: '1000g', calories: '31 kcal', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=500&q=80',
    stockQuantity: 10,
    isExclusive: true,
    brand: 'Kazi Farms',
  },
  {
    id: 'p-4',
    name: 'Ginger Fresh Root',
    categoryId: 'fruits-veg',
    categoryName: 'Fresh Fruits & Vegetable',
    unit: '250g',
    price: 1.99,
    rating: 4.7,
    reviewsCount: 54,
    description: 'Aromatic and pungent fresh ginger root. Adds incredible depth to teas, curries, and dressings.',
    nutritionInfo: { weight: '250g', calories: '80 kcal', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=500&q=80',
    stockQuantity: 12,
    isExclusive: true,
    brand: 'Individual Collection',
  },

  // Beverages
  {
    id: 'p-5',
    name: 'Classic Sparkling Cola',
    categoryId: 'beverages',
    categoryName: 'Beverages',
    unit: '355ml',
    price: 1.49,
    originalPrice: 1.99,
    rating: 4.5,
    reviewsCount: 340,
    description: 'Crisp, refreshing carbonated sparkling beverage with natural cola flavor.',
    nutritionInfo: { weight: '355ml', calories: '140 kcal', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=500&q=80',
    stockQuantity: 30,
    isBestSelling: true,
    brand: 'Generic Beverage Co.',
  },
  {
    id: 'p-6',
    name: 'Zero Sugar Cola Can',
    categoryId: 'beverages',
    categoryName: 'Beverages',
    unit: '355ml',
    price: 1.49,
    rating: 4.4,
    reviewsCount: 190,
    description: 'Zero sugar cola offering full classic taste without calories.',
    nutritionInfo: { weight: '355ml', calories: '0 kcal', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&w=500&q=80',
    stockQuantity: 20,
    brand: 'Generic Beverage Co.',
  },
  {
    id: 'p-7',
    name: 'Lemon Lime Citrus Soda',
    categoryId: 'beverages',
    categoryName: 'Beverages',
    unit: '355ml',
    price: 1.29,
    rating: 4.6,
    reviewsCount: 145,
    description: 'Zesty lemon-lime soda for an invigorating burst of citrus flavor.',
    nutritionInfo: { weight: '355ml', calories: '130 kcal', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?auto=format&fit=crop&w=500&q=80',
    stockQuantity: 18,
    isBestSelling: true,
    brand: 'Generic Beverage Co.',
  },
  {
    id: 'p-8',
    name: 'Natural Apple Juice Box',
    categoryId: 'beverages',
    categoryName: 'Beverages',
    unit: '2L',
    price: 3.99,
    rating: 4.9,
    reviewsCount: 96,
    description: '100% pure pressed apple juice with no added sugar or artificial preservatives.',
    nutritionInfo: { weight: '2000ml', calories: '110 kcal per glass', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=500&q=80',
    stockQuantity: 8,
    brand: 'Individual Collection',
  },
  {
    id: 'p-9',
    name: 'Orange Juice Fresh Pressed',
    categoryId: 'beverages',
    categoryName: 'Beverages',
    unit: '1L',
    price: 4.49,
    rating: 4.8,
    reviewsCount: 210,
    description: 'Pure sun-ripened orange juice with high pulp and Vitamin C.',
    nutritionInfo: { weight: '1000ml', calories: '120 kcal', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=500&q=80',
    stockQuantity: 14,
    isExclusive: true,
    brand: 'Individual Collection',
  },

  // Dairy & Eggs
  {
    id: 'p-10',
    name: 'Farm Fresh Brown Eggs',
    categoryId: 'dairy-eggs',
    categoryName: 'Dairy & Eggs',
    unit: '12 pcs',
    price: 3.49,
    rating: 4.9,
    reviewsCount: 430,
    description: 'Grade-A pasture raised brown eggs from free-roaming hens.',
    nutritionInfo: { weight: '700g', calories: '70 kcal per egg', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=500&q=80',
    stockQuantity: 30,
    isBestSelling: true,
    brand: 'Kazi Farms',
  },
  {
    id: 'p-11',
    name: 'Whole Fresh Milk 1L',
    categoryId: 'dairy-eggs',
    categoryName: 'Dairy & Eggs',
    unit: '1L',
    price: 2.19,
    rating: 4.7,
    reviewsCount: 310,
    description: 'Rich, creamy whole milk pasteurized for peak freshness and calcium content.',
    nutritionInfo: { weight: '1000ml', calories: '150 kcal', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=500&q=80',
    stockQuantity: 22,
    isBestSelling: true,
    brand: 'Ifad',
  },

  // Cooking Oil & Ghee
  {
    id: 'p-12',
    name: 'Extra Virgin Olive Oil',
    categoryId: 'oil-ghee',
    categoryName: 'Cooking Oil & Ghee',
    unit: '500ml',
    price: 8.99,
    originalPrice: 10.49,
    rating: 4.9,
    reviewsCount: 180,
    description: 'Cold-pressed extra virgin olive oil imported from Mediterranean groves.',
    nutritionInfo: { weight: '500ml', calories: '120 kcal per tbsp', organic: true },
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=500&q=80',
    stockQuantity: 10,
    isExclusive: true,
    brand: 'Individual Collection',
  },

  // Bakery & Snacks
  {
    id: 'p-13',
    name: 'Egg Noodles Pack',
    categoryId: 'bakery-snacks',
    categoryName: 'Bakery & Snacks',
    unit: '400g',
    price: 1.89,
    rating: 4.6,
    reviewsCount: 165,
    description: 'Quick-cooking wheat egg noodles, ideal for soups and Asian stir-fry recipes.',
    nutritionInfo: { weight: '400g', calories: '350 kcal', organic: false },
    imageUrl: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=500&q=80',
    stockQuantity: 20,
    brand: 'Ifad',
  },
];
